import type { EvidenceCard } from "./core.ts";

export const stages = ["precursor", "coinage", "formalization", "adoption", "transfer", "current-use"] as const;
export type Stage = typeof stages[number];
export const normalizeDisplay = (v: string) => v.normalize("NFKC").trim().replace(/\s+/gu, " ");
export const normalizeComparable = (v: string) => normalizeDisplay(v).toLowerCase();
export function canonicalUrl(raw: string) { const url = new URL(raw); url.protocol = url.protocol.toLowerCase(); url.hostname = url.hostname.toLowerCase(); url.hash = ""; if ((url.protocol === "http:" && url.port === "80") || (url.protocol === "https:" && url.port === "443")) url.port = ""; if (!url.pathname) url.pathname = "/"; const q = [...url.searchParams].filter(([k]) => !(/^utm_/i.test(k) || /^(gclid|fbclid)$/i.test(k))).sort(([a,av],[b,bv]) => a.localeCompare(b) || av.localeCompare(bv)); url.search = ""; for (const [k,v] of q) url.searchParams.append(k,v); return url.toString(); }
export function trustFor(url: string, title: string, publishedDate = "") { const host = new URL(url).hostname; const reasons: string[] = []; let score = 35; if (/\.edu$|\.gov$|doi\.org|arxiv\.org/i.test(host)) { score += 35; reasons.push("institutional or primary-research domain"); } if (/university|journal|press|archive|museum|library/i.test(`${host} ${title}`)) { score += 20; reasons.push("academic, archival, or publisher indicator"); } if (publishedDate) { score += 3; reasons.push("published date supplied by search result"); } if (/wikipedia|medium|blog/i.test(host)) { score -= 20; reasons.push("general secondary source"); } if (/\b(doi|paper|journal|archive|report)\b/i.test(title)) { score += 10; reasons.push("primary/research title indicator"); } return { trustScore: Math.max(0,Math.min(100,score)), trustReasons: reasons.length ? reasons : ["unknown source type; provisional heuristic"] }; }
export type Comparable = { subject: string; predicate: string; value: string; polarity: "support" | "deny"; scope: string };
export function conflictsFor(items: Array<{card: EvidenceCard; comparable: Comparable; sourceId: string}>) { const out: Array<{subject:string;predicate:string;scope:string;kind:"polarity"|"value";cardIds:string[];sourceIds:string[];message:string}> = []; for(let i=0;i<items.length;i++) for(let j=i+1;j<items.length;j++) { const a=items[i], b=items[j]; if(a.card.id===b.card.id||a.sourceId===b.sourceId) continue; if([a.comparable.subject,a.comparable.predicate,a.comparable.scope].map(normalizeComparable).join("\0") !== [b.comparable.subject,b.comparable.predicate,b.comparable.scope].map(normalizeComparable).join("\0")) continue; const polarity=a.comparable.polarity!==b.comparable.polarity; const value=normalizeComparable(a.comparable.value)!==normalizeComparable(b.comparable.value) && !!normalizeComparable(a.comparable.value) && !!normalizeComparable(b.comparable.value); if(polarity||value) out.push({subject:a.comparable.subject,predicate:a.comparable.predicate,scope:a.comparable.scope,kind:polarity?"polarity":"value",cardIds:[a.card.id,b.card.id],sourceIds:[a.sourceId,b.sourceId],message:"Heuristic review signal: comparable claims differ across independent source snapshots."}); } return out; }
export function gapQuestions(required: readonly Stage[], cards: EvidenceCard[], failed = new Set<Stage>()) { return required.filter(s=>!cards.some(c=>c.claimType===s)).map(stage=>({stage,reason: failed.has(stage)?"extraction-failed":"missing",question:`What reliable source documents ${stage} for this concept and scope?`})); }
