import { createHash, randomUUID } from "node:crypto";
import { isMathMode, planConceptResearch, renderConceptReport, toolError, validateEvidenceCards, type EvidenceCard, type MathMode, type ResearchPlan } from "./core.ts";
import { canonicalUrl, conflictsFor, gapQuestions, normalizeComparable, normalizeDisplay, stages, trustFor, type Comparable, type Stage } from "./analysis.ts";
import { CACHE_VERSION, containsCredential, ResearchStorage } from "./storage.ts";
import { fetchPageContent, searchWebPages } from "./keenable.ts";

type Search = typeof searchWebPages; type Fetch = typeof fetchPageContent;
export type EngineDeps = { search?: Search; fetch?: Fetch; storage?: ResearchStorage; now?: () => Date; beforeCommit?: () => void; beforeSnapshotCommit?: () => void };
const sha = (s: string) => createHash("sha256").update(s).digest("hex");
const stable = (value: unknown): string => JSON.stringify(value, (_k,v) => v && typeof v === "object" && !Array.isArray(v) ? Object.fromEntries(Object.keys(v).sort().map(k=>[k,(v as Record<string,unknown>)[k]])) : v);
const cacheArgs = (operation:string, args:Record<string,unknown>): unknown => Object.fromEntries(Object.keys(args).sort().map(k=>{ const value=args[k]; if(k==="url"&&typeof value==="string") { try{return [k,canonicalUrl(value)];}catch{return [k,value];} } if(operation==="search"&&k==="query"&&typeof value==="string") return [k,normalizeDisplay(value)]; return [k,value]; }));
const key = (operation: string, args: Record<string,unknown>) => sha(stable({cacheVersion:CACHE_VERSION,operation,args:cacheArgs(operation,args)}));
const nowText = (now: () => Date) => now().toISOString();
const required = (depth: string): Stage[] => depth === "brief" ? ["precursor","formalization","transfer","current-use"] : [...stages];
const sourceType = (url:string): EvidenceCard["sourceType"] => /doi\.org|arxiv\.org|\.edu\//i.test(url) ? "primary-paper" : /press|books\.google/i.test(url) ? "book" : /\.gov|museum|archive|library/i.test(url) ? "institutional-reference" : "other";
const strictPrompt = "Return only a JSON object or array. Each candidate must be {card:{claim,claimType,historicalContext,mechanism,problemSolved,concreteExample:{title,scenario,walkthrough,insight},frameworkSignificance,sourceType,publicationDate,evidenceSummary,confidence,inference,disputes,supports},comparableClaim:{subject,predicate,value,polarity,scope},evidenceLocator}. Do not provide URLs, source IDs, or prose.";
function parseCandidates(text:string) { const body = text.match(/```(?:json)?\s*([\s\S]*?)```/i)?.[1] ?? text; try { const x=JSON.parse(body); return Array.isArray(x)?x:(x&&typeof x==="object"?[x]:[]); } catch { return []; } }
function validLocator(locator:string, content:string) { return locator.length>0 && locator.length<=240 && (content.includes(locator)||/^(?:section|§|page|p\.|chapter|heading)\s*[-:\d]/i.test(locator)); }
const conservativeLocator = /^(?:section|§|page|p\.|chapter|heading)\b/i;
function dateQuoteSupports(locator:string, content:string, date:string) { return content.includes(locator) && !conservativeLocator.test(locator) && locator.includes(date); }
function validDate(value:unknown) { if(typeof value!=="string"||!/^\d{4}(?:-\d{2}(?:-\d{2})?)?$/.test(value)) return false; const [year,month,day]=value.split("-").map(Number); if(year<1||(month!==undefined&&(month<1||month>12))) return false; if(day===undefined) return true; const date=new Date(Date.UTC(year,month-1,day)); return date.getUTCFullYear()===year&&date.getUTCMonth()===month-1&&date.getUTCDate()===day; }
function comparableFrom(value:unknown): Comparable | null { if(!value||typeof value!=="object"||Array.isArray(value)) return null; const raw=value as Record<string,unknown>; if(!["subject","predicate","value","scope"].every(key=>typeof raw[key]==="string"&&normalizeDisplay(raw[key] as string))) return null; if(raw.polarity!=="support"&&raw.polarity!=="deny") return null; return {subject:normalizeDisplay(raw.subject as string),predicate:normalizeDisplay(raw.predicate as string),value:normalizeDisplay(raw.value as string),polarity:raw.polarity,scope:normalizeDisplay(raw.scope as string)}; }
function inputSettings(input: Record<string,unknown>) { return { language:(input.language??"zh-CN") as "zh-CN"|"en", audience:(input.audience??"beginner") as "beginner"|"intermediate"|"expert", depth:(input.depth??"standard") as "brief"|"standard"|"deep", mathMode:(input.mathMode??"portable") as MathMode, maxSources:Number(input.max_sources_per_query??3), maxIterations:Number(input.max_iterations??2) }; }
function normalizedSettings(value: Record<string,unknown>) { return { language:value.language, audience:value.audience, depth:value.depth, mathMode:value.mathMode ?? "portable", maxSources:value.maxSources, maxIterations:value.maxIterations }; }
function idText(s:string){ return normalizeComparable(s); }
function runError(code:string,message:string,runId?:string) { return { ok:false as const,error:{code,message},...(runId?{runId}:{})}; }

export class ResearchEngine {
  readonly storage: ResearchStorage; readonly search: Search; readonly fetch: Fetch; readonly now: () => Date; readonly beforeCommit?: () => void; readonly beforeSnapshotCommit?: () => void;
  constructor(deps: EngineDeps = {}) { this.storage=deps.storage??new ResearchStorage(); this.search=deps.search??searchWebPages; this.fetch=deps.fetch??fetchPageContent; this.now=deps.now??(()=>new Date()); this.beforeCommit=deps.beforeCommit; this.beforeSnapshotCommit=deps.beforeSnapshotCommit; }
  async cached(operation:string,args:Record<string,unknown>,ttl:number, fn:()=>Promise<any>, stats:any) { const cacheKey=key(operation,args), found=this.storage.cache(cacheKey); if(found) { stats.cacheHits++; if(found.status==="success") return {value:JSON.parse(String(found.payload_json)),cacheKey}; return {value:toolError(String(found.safe_error_code||"CACHED_FAILURE"),"A cached operation failure is still active."),cacheKey}; } const raw=await fn(), value=containsCredential(raw)?toolError("SENSITIVE_CONTENT","Sensitive remote data was rejected."):raw; const failed=!value?.ok; this.storage.putCache(cacheKey,operation,value,ttl,failed?"failed":"success",failed?String(value?.error?.code||"OPERATION_FAILED"):undefined); return {value,cacheKey}; }
  async run(input:Record<string,unknown>) {
    if(containsCredential(input)) return toolError("SENSITIVE_CONTENT","Sensitive values are not accepted in research input.");
    const concept=typeof input.concept==="string"?normalizeDisplay(input.concept):"", scope=typeof input.scope==="string"?normalizeDisplay(input.scope):""; if(!concept||!scope) return toolError("INVALID_ARGUMENT","concept and scope must be nonempty.");
    const settings=inputSettings(input); if(!["zh-CN","en"].includes(settings.language)||!["beginner","intermediate","expert"].includes(settings.audience)||!["brief","standard","deep"].includes(settings.depth)||!isMathMode(settings.mathMode)||!Number.isInteger(settings.maxSources)||settings.maxSources<1||settings.maxSources>5||!Number.isInteger(settings.maxIterations)||settings.maxIterations<1||settings.maxIterations>3) return toolError("INVALID_ARGUMENT","research_concept arguments do not match schema.");
    const conceptKey=sha(stable({v:1,concept:idText(concept),scope:idText(scope),language:settings.language})); let runId=typeof input.resume_run_id==="string"?input.resume_run_id:""; let row=runId?this.storage.run(runId):null;
    if(runId && !row) return toolError("RUN_NOT_FOUND","Research run was not found.");
    if(row) { const old=JSON.parse(String(row.settings_json)); if(String(row.concept_key)!==conceptKey || stable(normalizedSettings(old))!==stable(settings)) return toolError("RESUME_MISMATCH","Resume settings or concept do not match the persisted run."); }
    else { runId=`run_${randomUUID()}`; const plan=planConceptResearch({concept,language:settings.language,audience:settings.audience,depth:settings.depth}).plan; const time=nowText(this.now); try { this.storage.db.query("INSERT INTO research_runs(run_id,concept_key,settings_json,plan_json,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)").run(runId,conceptKey,stable(settings),JSON.stringify(plan),"partial",time,time); } catch { return toolError("STORAGE_ERROR","Unable to initialize research storage."); } row=this.storage.run(runId); }
    const plan=JSON.parse(String(row!.plan_json)) as ResearchPlan; let completed=Number(row!.iterations_completed); const req=required(settings.depth); let allCards: EvidenceCard[]=[]; let comparables:Array<{card:EvidenceCard;comparable:Comparable;sourceId:string}>=[]; let sources:any[]=[]; let warnings:string[]=[]; const stats={queries:0,searchResults:0,dedupedSources:0,fetchedSources:0,extractionAttempts:0,validCards:0,cacheHits:0};
    const oldSnap=this.storage.snapshot(runId); if(oldSnap) { if(completed>=settings.maxIterations) return oldSnap; allCards=oldSnap.evidenceCards; sources=oldSnap.sources; warnings=oldSnap.warnings; for(const k of Object.keys(stats) as Array<keyof typeof stats>) stats[k]=Number(oldSnap.stats?.[k]??0); comparables=(this.storage.db.query("SELECT ec.card_json,ec.comparable_json,ecs.source_id FROM evidence_cards ec JOIN evidence_card_sources ecs ON ecs.card_id=ec.card_id WHERE ec.run_id=?").all(runId) as Array<{card_json:string;comparable_json:string|null;source_id:string}>).flatMap(row=>{ if(!row.comparable_json) return []; const comparable=comparableFrom(JSON.parse(row.comparable_json)); return comparable?[{card:JSON.parse(row.card_json) as EvidenceCard,comparable,sourceId:row.source_id}]:[]; }); }
    try { for(let iteration=completed+1; iteration<=settings.maxIterations; iteration++) { const missing=gapQuestions(req,allCards).map(g=>g.stage as Stage); if(iteration>1 && !missing.length) break; const queries=iteration===1 ? plan.searchQueryGroups.flatMap(x=>x.queries.map(q=>`${q} ${scope}`)) : missing.map(s=>`${concept} ${scope} ${s}`); const localSources=new Map<string,any>(); const snapshots:any[]=[]; const priorHashes=new Set((this.storage.db.query("SELECT ss.content_hash FROM run_sources rs JOIN source_snapshots ss ON ss.source_snapshot_id=rs.source_snapshot_id WHERE rs.run_id=?").all(runId) as Array<{content_hash:string}>).map(row=>row.content_hash)); const contentHashes=new Set(priorHashes); const newCards: Array<{card:EvidenceCard;snapshot:any;locator:string;comparable:Comparable}> = [];
      for(const query of queries) { stats.queries++; const {value:searchResult}=await this.cached("search",{query},86400000,()=>this.search({query}),stats); if(!searchResult?.ok) { warnings.push(`search failed: ${query}`); continue; } const results=searchResult.results as any[]; stats.searchResults+=results.length; for(const result of results) { let url:string; try{url=canonicalUrl(String(result.url));}catch{continue;} if(localSources.has(url))continue; const publishedDate=String(result.publishedDate||""); const t=trustFor(url,String(result.title||url),publishedDate); localSources.set(url,{canonicalUrl:url,title:normalizeDisplay(String(result.title||url)),domain:new URL(url).hostname,sourceType:sourceType(url),...t,publishedDate}); } }
      const candidates=[...localSources.values()].sort((a,b)=>b.trustScore-a.trustScore||a.canonicalUrl.localeCompare(b.canonicalUrl)).slice(0,queries.length*settings.maxSources); stats.dedupedSources+=candidates.length;
      for(const s of candidates) { const sourceId=sha(s.canonicalUrl); const {value:page,cacheKey}=await this.cached("fetch",{url:s.canonicalUrl},604800000,()=>this.fetch({url:s.canonicalUrl,max_chars:200000}),stats); if(!page?.ok||!normalizeDisplay(String(page.content||""))) { warnings.push(page?.error?.code==="SENSITIVE_CONTENT"?`sensitive content rejected: ${s.canonicalUrl}`:`fetch failed: ${s.canonicalUrl}`); continue; } stats.fetchedSources++; const content=String(page.content); if(containsCredential(content)) { warnings.push(`sensitive content rejected: ${s.canonicalUrl}`); continue; } const contentHash=sha(content), snapshot={sourceId,sourceSnapshotId:sha(sourceId+contentHash),contentHash,cacheKey,retrievedAt:nowText(this.now),fetchStatus:"fetched" as const,content}; s.title=normalizeDisplay(String(page.title||s.title)); if(contentHashes.has(contentHash)){warnings.push(`content duplicate: ${s.canonicalUrl}`);continue;} contentHashes.add(contentHash); snapshots.push(snapshot); const {value:extract}=await this.cached("extraction",{url:s.canonicalUrl,contentHash,promptVersion:CACHE_VERSION},2592000000,()=>this.fetch({url:s.canonicalUrl,max_chars:200000,prompt:strictPrompt}),stats); stats.extractionAttempts++; if(!extract?.ok||containsCredential(extract.content)) { warnings.push(`extraction failed: ${s.canonicalUrl}`); continue; } const parsed=parseCandidates(String(extract.content||"")); if(!parsed.length) { warnings.push(`extraction failed: ${s.canonicalUrl}`); continue; }
        for(const candidate of parsed) { const raw=candidate?.card, locator=typeof candidate?.evidenceLocator==="string"?normalizeDisplay(candidate.evidenceLocator):""; if(!raw||!validLocator(locator,content)) { warnings.push(`provenance rejected: ${s.canonicalUrl}`); continue; } const comparable=comparableFrom(candidate?.comparableClaim); if(!comparable) { warnings.push(`comparable claim rejected: ${s.canonicalUrl}`); continue; } const candidateDate=validDate(raw.publicationDate)?raw.publicationDate:null; const publicationDate=validDate(s.publishedDate)?s.publishedDate:(candidateDate&&dateQuoteSupports(locator,content,candidateDate)?candidateDate:null); if(!publicationDate) { warnings.push(`candidate rejected: publication date lacks source provenance: ${s.canonicalUrl}`); continue; } const fingerprint=sha(stable({runId,claimType:raw.claimType,subject:normalizeComparable(comparable.subject),predicate:normalizeComparable(comparable.predicate),value:normalizeComparable(comparable.value),polarity:comparable.polarity,scope:normalizeComparable(comparable.scope),sourceId})); const card:EvidenceCard={...raw,id:`${runId}_${fingerprint}`,sourceUrl:s.canonicalUrl,sourceTitle:s.title,sourceType:s.sourceType,publicationDate,disputes:Array.isArray(raw.disputes)?raw.disputes:[],supports:[],concreteExample:raw.concreteExample}; const validation=validateEvidenceCards([card]); if(!validation.valid) { warnings.push(`candidate invalid: ${s.canonicalUrl}`); continue; } if(!allCards.some(x=>x.id===card.id)&&!newCards.some(x=>x.card.id===card.id)) newCards.push({card,snapshot,locator,comparable}); }
      }
      const nextCards=[...allCards,...newCards.map(x=>x.card)], nextComparables=[...comparables,...newCards.map(x=>({card:x.card,comparable:x.comparable,sourceId:x.snapshot.sourceId}))], gaps=gapQuestions(req,nextCards,new Set<Stage>()), conflicts=conflictsFor(nextComparables).map(c=>({id:`${runId}_${sha(stable(c))}`,...c})); const nextSources=[...sources,...candidates.filter(s=>!sources.some((p:any)=>p.sourceId===sha(s.canonicalUrl)))].map(({publishedDate,...s})=>({...s,sourceId:sha(s.canonicalUrl),retrievedAt:nowText(this.now),contentHash:"",fetchStatus:"failed",cacheKey:""})); for(const z of snapshots) { const target=nextSources.find((s:any)=>s.sourceId===z.sourceId); if(target) Object.assign(target,{contentHash:z.contentHash,fetchStatus:"fetched",cacheKey:z.cacheKey,retrievedAt:z.retrievedAt}); }
      const iterStatus:any=nextCards.length===0?"partial":(gaps.length||conflicts.length||nextCards.some(c=>c.confidence==="low")||warnings.length?"needs-review":"complete"); const rendered=nextCards.length?renderConceptReport({concept,plan,evidenceCards:nextCards,language:settings.language,mathMode:settings.mathMode}):null; const iterationSnapshot={ok:true as const,runId,conceptKey,scope,status:nextCards.length===0?iterStatus:(rendered?.ok?iterStatus:"needs-review"),iterationsCompleted:iteration,maxIterations:settings.maxIterations,plan,sources:nextSources,evidenceCards:nextCards,conflicts,gaps,followUpQuestions:gaps.map(g=>g.question),report:rendered?.ok?rendered.report:null,stats:{...stats,validCards:nextCards.length},warnings:[...new Set(warnings)]};
      this.beforeCommit?.(); this.storage.transaction(()=>{ for(const s of candidates) { const sid=sha(s.canonicalUrl); this.storage.db.query("INSERT INTO sources VALUES(?,?,?,?,?,?,?) ON CONFLICT(source_id) DO UPDATE SET title=excluded.title,trust_score=excluded.trust_score,trust_reasons_json=excluded.trust_reasons_json").run(sid,s.canonicalUrl,s.title,s.domain,s.sourceType,s.trustScore,JSON.stringify(s.trustReasons)); } for(const z of snapshots) { this.storage.db.query("INSERT OR IGNORE INTO source_snapshots VALUES(?,?,?,?,?,?,?)").run(z.sourceSnapshotId,z.sourceId,z.retrievedAt,z.contentHash,z.cacheKey,"fetched",z.content); this.storage.db.query("INSERT OR IGNORE INTO run_sources VALUES(?,?,?,?)").run(runId,z.sourceSnapshotId,z.sourceId,iteration); } for(const x of newCards) { const z=x.snapshot; this.storage.db.query("INSERT OR IGNORE INTO evidence_cards(card_id,run_id,fingerprint,card_json,comparable_json) VALUES(?,?,?,?,?)").run(x.card.id,runId,x.card.id.slice(runId.length+1),JSON.stringify(x.card),JSON.stringify(x.comparable)); this.storage.db.query("INSERT OR IGNORE INTO evidence_card_sources VALUES(?,?,?,?,?,?,?)").run(x.card.id,z.sourceSnapshotId,z.sourceId,z.contentHash,x.locator,CACHE_VERSION,nowText(this.now)); } this.storage.db.query("DELETE FROM conflicts WHERE run_id=?").run(runId); this.storage.db.query("DELETE FROM gaps WHERE run_id=?").run(runId); for(const c of conflicts) this.storage.db.query("INSERT INTO conflicts VALUES(?,?,?)").run(c.id,runId,JSON.stringify(c)); for(const gap of gaps) this.storage.db.query("INSERT INTO gaps VALUES(?,?,?)").run(`${runId}_${gap.stage}`,runId,JSON.stringify({id:`${runId}_${gap.stage}`,...gap})); this.storage.db.query("INSERT OR IGNORE INTO research_iterations VALUES(?,?,?,?)").run(runId,iteration,key("iteration",{runId,iteration}),nowText(this.now)); this.storage.db.query("DELETE FROM graph_nodes WHERE run_id=?").run(runId); this.storage.db.query("DELETE FROM graph_edges WHERE run_id=?").run(runId); this.beforeSnapshotCommit?.(); const graph=this.graphFor(iterationSnapshot); for(const n of graph.nodes)this.storage.db.query("INSERT INTO graph_nodes VALUES(?,?,?,?,?)").run(n.id,runId,n.type,n.label,JSON.stringify(n.data)); for(const e of graph.edges)this.storage.db.query("INSERT INTO graph_edges VALUES(?,?,?,?,?,?)").run(e.id,runId,e.type,e.from,e.to,JSON.stringify(e.data)); this.storage.db.query("UPDATE research_runs SET snapshot_json=?,status=?,iterations_completed=?,updated_at=? WHERE run_id=?").run(JSON.stringify(iterationSnapshot),iterationSnapshot.status,iteration,nowText(this.now),runId); }); allCards=nextCards; comparables=nextComparables; sources=nextSources; completed=iteration; if(!gaps.length) break;
    } } catch (error) { if(!completed) return runError("STORAGE_ERROR","Research iteration could not be committed.",runId); warnings.push("iteration interrupted before commit; resume retries it."); }
    const persisted=this.storage.snapshot(runId); if(!persisted) return runError("STORAGE_ERROR","Unable to persist research snapshot.",runId); return persisted;
  }
  get(runId:string) { const snapshot=this.storage.snapshot(runId); return snapshot??(this.storage.run(runId)?runError("RUN_NOT_READY","Research run exists but has no committed snapshot.",runId):toolError("RUN_NOT_FOUND","Research run was not found.")); }
  graph(runId:string) { const snap=this.storage.snapshot(runId); return snap?this.graphFor(snap):toolError("RUN_NOT_FOUND","Research run was not found."); }
  graphFor(snapshot:any) { const prefix=snapshot.runId; const nodes:any[]=[{id:`${prefix}:concept`,type:"concept",label:snapshot.plan.concept,data:{conceptKey:snapshot.conceptKey}}]; const edges:any[]=[]; const snapshotForCard=(cardId:string)=>this.storage.db.query("SELECT source_snapshot_id FROM evidence_card_sources WHERE card_id=?").get(cardId) as {source_snapshot_id:string}|null; for(const stage of required(snapshot.plan.settings.depth)){const id=`${prefix}:stage:${stage}`;nodes.push({id,type:"stage",label:stage,data:{}});edges.push({id:`${prefix}:has:${stage}`,type:"has_stage",from:`${prefix}:concept`,to:id,data:{}});} for(const card of snapshot.evidenceCards){const cid=`${prefix}:card:${card.id}`;nodes.push({id:cid,type:"card",label:card.claim,data:{claimType:card.claimType}});edges.push({id:`${prefix}:support:${card.id}`,type:"supports_stage",from:cid,to:`${prefix}:stage:${card.claimType}`,data:{}});} for(const source of snapshot.sources){const sid=`${prefix}:source:${source.sourceId}`;nodes.push({id:sid,type:"source",label:source.title,data:{sourceSnapshotId:source.contentHash?sha(source.sourceId+source.contentHash):null,canonicalUrl:source.canonicalUrl}}); for(const card of snapshot.evidenceCards.filter((c:EvidenceCard)=>c.sourceUrl===source.canonicalUrl)){const original=snapshotForCard(card.id); edges.push({id:`${prefix}:source:${card.id}`,type:"sourced_from",from:`${prefix}:card:${card.id}`,to:sid,data:{sourceSnapshotId:original?.source_snapshot_id??null}});}} for(const c of snapshot.conflicts)edges.push({id:`${prefix}:conflict:${c.id}`,type:"conflicts_with",from:`${prefix}:card:${c.cardIds[0]}`,to:`${prefix}:card:${c.cardIds[1]}`,data:{conflictId:c.id}}); return {ok:true as const,runId:prefix,conceptKey:snapshot.conceptKey,nodes,edges}; }
}
