import { VERSION, isMathMode, planConceptResearch, renderConceptReport, toolError, validateEvidenceCards } from "./core.ts";
import { fetchPageContent, searchWebPages } from "./keenable.ts";
import { ResearchEngine } from "./research-engine.ts";
import fixture from "./fixtures/entropy.json" with { type: "json" };

const dateSchema = { type: "string", pattern: "^\\d{4}(?:-\\d{2}(?:-\\d{2})?)?$", description: "Calendar-validated YYYY, YYYY-MM, or YYYY-MM-DD." };
const exampleSchema = { type: "object", additionalProperties: false, required: ["title", "scenario", "walkthrough", "insight"], properties: { title: { type: "string", minLength: 1 }, scenario: { type: "string", minLength: 1 }, walkthrough: { type: "array", minItems: 1, items: { type: "string", minLength: 1 } }, insight: { type: "string", minLength: 1 } } };
const cardSchema = { type: "object", additionalProperties: false, required: ["id", "claim", "claimType", "historicalContext", "mechanism", "problemSolved", "concreteExample", "frameworkSignificance", "sourceUrl", "sourceTitle", "sourceType", "publicationDate", "evidenceSummary", "confidence", "inference", "disputes", "supports"], properties: { id: { type: "string", minLength: 1 }, claim: { type: "string", minLength: 1 }, claimType: { enum: ["precursor", "coinage", "formalization", "adoption", "transfer", "current-use"] }, historicalContext: { type: "string", minLength: 1 }, mechanism: { type: "string", minLength: 1 }, problemSolved: { type: "string", minLength: 1 }, concreteExample: exampleSchema, frameworkSignificance: { type: "string", minLength: 1 }, sourceUrl: { type: "string", pattern: "^https?://" }, sourceTitle: { type: "string", minLength: 1 }, sourceType: { enum: ["primary-paper", "book", "academic-review", "institutional-reference", "other"] }, publicationDate: dateSchema, evidenceSummary: { type: "string", minLength: 1 }, confidence: { enum: ["high", "medium", "low"] }, inference: { type: "boolean" }, disputes: { type: "array", items: { type: "string", minLength: 1 } }, supports: { type: "array", items: { type: "string", minLength: 1 } } } };
const planSchema = { type: "object", additionalProperties: false, required: ["version", "concept", "settings", "disambiguationPrompts", "researchDimensions", "searchQueryGroups", "evidenceRequirements", "status"], properties: { version: { type: "string", minLength: 1 }, concept: { type: "string", minLength: 1 }, settings: { type: "object", additionalProperties: false, required: ["language", "audience", "depth"], properties: { language: { enum: ["zh-CN", "en"] }, audience: { enum: ["beginner", "intermediate", "expert"] }, depth: { enum: ["brief", "standard", "deep"] } } }, disambiguationPrompts: { type: "array", items: { type: "string", minLength: 1 } }, researchDimensions: { type: "array", items: { type: "object", additionalProperties: false, required: ["order", "name"], properties: { order: { type: "integer", minimum: 1 }, name: { type: "string", minLength: 1 } } } }, searchQueryGroups: { type: "array", items: { type: "object", additionalProperties: false, required: ["purpose", "queries"], properties: { purpose: { type: "string", minLength: 1 }, queries: { type: "array", items: { type: "string", minLength: 1 } } } } }, evidenceRequirements: { type: "array", items: { type: "string", minLength: 1 } }, status: { const: "planned" } } };
const errorSchema = { type: "object", additionalProperties: false, required: ["ok", "error"], properties: { ok: { const: false }, runId: { type: "string", minLength: 1 }, error: { type: "object", additionalProperties: false, required: ["code", "message"], properties: { code: { type: "string" }, message: { type: "string" }, details: {} } } } };
const validationSchema = { type: "object", additionalProperties: false, required: ["ok", "valid", "errors", "warnings", "normalizedCards"], properties: { ok: { const: true }, valid: { type: "boolean" }, errors: { type: "array", items: { type: "object", additionalProperties: false, required: ["code", "path", "message"], properties: { code: { type: "string" }, path: { type: "string" }, message: { type: "string" } } } }, warnings: { type: "array", items: { type: "object", additionalProperties: false, required: ["code", "path", "message"], properties: { code: { type: "string" }, path: { type: "string" }, message: { type: "string" } } } }, normalizedCards: { type: "array", items: cardSchema } } };
const demoLabelSchema = { type: "object", additionalProperties: false, required: ["kind", "lastReviewed"], properties: { kind: { const: "demo-fixture" }, lastReviewed: dateSchema, freshness: { const: "bundled-offline-fixture" } } };
const citationSchema = { type: "object", additionalProperties: false, required: ["id", "title", "url", "publicationDate", "sourceType"], properties: { id: { type: "string", minLength: 1 }, title: { type: "string", minLength: 1 }, url: { type: "string", pattern: "^https?://" }, publicationDate: dateSchema, sourceType: { enum: ["primary-paper", "book", "academic-review", "institutional-reference", "other"] } } };
const reportItemSchema = { type: "object", additionalProperties: false, required: ["claim", "date", "historicalContext", "mechanism", "problemSolved", "concreteExample", "frameworkSignificance", "citation", "inference", "disputes"], properties: { claim: { type: "string", minLength: 1 }, date: dateSchema, historicalContext: { type: "string", minLength: 1 }, mechanism: { type: "string", minLength: 1 }, problemSolved: { type: "string", minLength: 1 }, concreteExample: exampleSchema, frameworkSignificance: { type: "string", minLength: 1 }, citation: citationSchema, inference: { type: "boolean" }, disputes: { type: "array", items: { type: "string", minLength: 1 } } } };
const problemChainGroupSchema = { type: "object", additionalProperties: false, required: ["stage", "claims"], properties: { stage: { enum: ["precursor", "coinage", "formalization", "adoption"] }, claims: { type: "array", items: reportItemSchema } } };
const uncertaintySchema = { type: "object", additionalProperties: false, required: ["claim", "reasons"], properties: { claim: { type: "string", minLength: 1 }, reasons: { type: "array", items: { type: "string", minLength: 1 } } } };
const mathModeSchema = { enum: ["portable", "latex", "html"], description: "portable is plain Markdown with readable Unicode fallbacks; latex uses $...$ and $$...$$; html includes a standalone MathJax document." };
const reportSchema = { type: "object", additionalProperties: false, required: ["title", "summary", "timeline", "problemChain", "crossDomainTransfers", "currentLandscape", "learningPath", "uncertainties", "citations", "markdown"], properties: { title: { type: "string", minLength: 1 }, summary: { type: "string", minLength: 1 }, timeline: { type: "array", items: reportItemSchema }, problemChain: { type: "array", items: problemChainGroupSchema }, crossDomainTransfers: { type: "array", items: reportItemSchema }, currentLandscape: { type: "array", items: reportItemSchema }, learningPath: { type: "array", items: { type: "string", minLength: 1 } }, uncertainties: { type: "array", items: uncertaintySchema }, citations: { type: "array", items: citationSchema }, mathMode: mathModeSchema, markdown: { type: "string", minLength: 1 }, html: { anyOf: [{ type: "string", minLength: 1 }, { type: "null" }] } } };
const labeledEvidenceCardSchema = { type: "object", additionalProperties: false, required: ["demo", "provenance", "card"], properties: { demo: { const: true }, provenance: demoLabelSchema, card: cardSchema } };
const labeledDatasetSchema = { type: "object", additionalProperties: false, required: ["demo", "provenance", "concept", "plan", "evidenceCards"], properties: { demo: { const: true }, provenance: demoLabelSchema, concept: { type: "string", minLength: 1 }, plan: planSchema, evidenceCards: { type: "array", items: labeledEvidenceCardSchema } } };
const labeledReportSchema = { type: "object", additionalProperties: false, required: ["demo", "provenance", "report"], properties: { demo: { const: true }, provenance: demoLabelSchema, report: reportSchema } };
const labeledValidationSchema = { type: "object", additionalProperties: false, required: ["demo", "provenance", "validation"], properties: { demo: { const: true }, provenance: demoLabelSchema, validation: validationSchema } };
const searchResultSchema = { type: "object", additionalProperties: false, required: ["title", "url", "description"], properties: { title: { type: "string" }, url: { type: "string" }, description: { type: "string" }, publishedDate: { type: "string" } } };
const sourceRecordSchema = { type: "object", additionalProperties: false, required: ["sourceId", "canonicalUrl", "title", "domain", "sourceType", "trustScore", "trustReasons", "retrievedAt", "contentHash", "fetchStatus", "cacheKey"], properties: { sourceId:{type:"string",minLength:1},canonicalUrl:{type:"string",pattern:"^https?://"},title:{type:"string",minLength:1},domain:{type:"string",minLength:1},sourceType:{enum:["primary-paper","book","academic-review","institutional-reference","other"]},trustScore:{type:"integer",minimum:0,maximum:100},trustReasons:{type:"array",items:{type:"string"}},retrievedAt:{type:"string",minLength:1},contentHash:{type:"string"},fetchStatus:{enum:["fetched","failed"]},cacheKey:{type:"string"} } };
const conflictSchema = { type:"object",additionalProperties:false,required:["id","subject","predicate","scope","kind","cardIds","sourceIds","message"],properties:{id:{type:"string",minLength:1},subject:{type:"string"},predicate:{type:"string"},scope:{type:"string"},kind:{enum:["polarity","value"]},cardIds:{type:"array",items:{type:"string",minLength:1}},sourceIds:{type:"array",items:{type:"string",minLength:1}},message:{type:"string",minLength:1}} };
const gapSchema = { type:"object",additionalProperties:false,required:["stage","reason","question"],properties:{stage:{enum:["precursor","coinage","formalization","adoption","transfer","current-use"]},reason:{enum:["missing","extraction-failed","source-failed"]},question:{type:"string",minLength:1}} };
const researchSuccessSchema = { type:"object",additionalProperties:false,required:["ok","runId","conceptKey","scope","status","iterationsCompleted","maxIterations","plan","sources","evidenceCards","conflicts","gaps","followUpQuestions","report","stats","warnings"],properties:{ok:{const:true},runId:{type:"string",minLength:1},conceptKey:{type:"string",minLength:1},scope:{type:"string",minLength:1},status:{enum:["complete","needs-review","partial","failed"]},iterationsCompleted:{type:"integer",minimum:0},maxIterations:{type:"integer",minimum:1,maximum:3},plan:planSchema,sources:{type:"array",items:sourceRecordSchema},evidenceCards:{type:"array",items:cardSchema},conflicts:{type:"array",items:conflictSchema},gaps:{type:"array",items:gapSchema},followUpQuestions:{type:"array",items:{type:"string",minLength:1}},report:{anyOf:[reportSchema,{type:"null"}]},stats:{type:"object",additionalProperties:false,required:["queries","searchResults","dedupedSources","fetchedSources","extractionAttempts","validCards","cacheHits"],properties:{queries:{type:"integer",minimum:0},searchResults:{type:"integer",minimum:0},dedupedSources:{type:"integer",minimum:0},fetchedSources:{type:"integer",minimum:0},extractionAttempts:{type:"integer",minimum:0},validCards:{type:"integer",minimum:0},cacheHits:{type:"integer",minimum:0}}},warnings:{type:"array",items:{type:"string",minLength:1}}} };
const graphNodeDataSchema = {type:"object",additionalProperties:false,properties:{conceptKey:{type:"string",minLength:1},claimType:{enum:["precursor","coinage","formalization","adoption","transfer","current-use"]},sourceSnapshotId:{anyOf:[{type:"string",minLength:1},{type:"null"}]},canonicalUrl:{type:"string",pattern:"^https?://"}}};
const graphEdgeDataSchema = {type:"object",additionalProperties:false,properties:{sourceSnapshotId:{anyOf:[{type:"string",minLength:1},{type:"null"}]},conflictId:{type:"string",minLength:1}}};
const graphSchema = {type:"object",additionalProperties:false,required:["ok","runId","conceptKey","nodes","edges"],properties:{ok:{const:true},runId:{type:"string",minLength:1},conceptKey:{type:"string",minLength:1},nodes:{type:"array",items:{type:"object",additionalProperties:false,required:["id","type","label","data"],properties:{id:{type:"string",minLength:1},type:{enum:["concept","stage","card","source"]},label:{type:"string",minLength:1},data:graphNodeDataSchema}}},edges:{type:"array",items:{type:"object",additionalProperties:false,required:["id","type","from","to","data"],properties:{id:{type:"string",minLength:1},type:{enum:["has_stage","supports_stage","sourced_from","conflicts_with"]},from:{type:"string",minLength:1},to:{type:"string",minLength:1},data:graphEdgeDataSchema}}}}};
const toolSchemas = {
  plan_concept_research: { inputSchema: { type: "object", additionalProperties: false, required: ["concept"], properties: { concept: { type: "string", minLength: 1 }, language: { enum: ["zh-CN", "en"] }, audience: { enum: ["beginner", "intermediate", "expert"] }, depth: { enum: ["brief", "standard", "deep"] } } }, outputSchema: { oneOf: [errorSchema, { type: "object", additionalProperties: false, required: ["ok", "plan"], properties: { ok: { const: true }, plan: planSchema } }] } },
  get_demo_concept: { inputSchema: { type: "object", additionalProperties: false, required: ["concept"], properties: { concept: { enum: ["entropy", "熵"] }, language: { enum: ["zh-CN"], description: "Only the bundled Chinese demo is available." } } }, outputSchema: { oneOf: [errorSchema, { type: "object", additionalProperties: false, required: ["ok", "demo", "provenance", "dataset", "report", "validation"], properties: { ok: { const: true }, demo: { const: true }, provenance: demoLabelSchema, dataset: labeledDatasetSchema, report: labeledReportSchema, validation: labeledValidationSchema } }] } },
  validate_evidence_cards: { inputSchema: { type: "object", additionalProperties: false, required: ["cards"], properties: { cards: { type: "array", items: cardSchema } } }, outputSchema: { oneOf: [errorSchema, validationSchema] } },
  render_concept_report: { inputSchema: { type: "object", additionalProperties: false, required: ["concept", "plan", "evidenceCards"], properties: { concept: { type: "string", minLength: 1 }, plan: planSchema, evidenceCards: { type: "array", items: cardSchema }, language: { enum: ["zh-CN", "en"] }, mathMode: mathModeSchema } }, outputSchema: { oneOf: [errorSchema, { type: "object", additionalProperties: false, required: ["ok", "report", "validation"], properties: { ok: { const: true }, report: reportSchema, validation: validationSchema } }] } },
  search_web_pages: { inputSchema: { type: "object", additionalProperties: false, required: ["query"], properties: { query: { type: "string", minLength: 1 }, site: { type: "string" }, published_after: { type: "string" }, published_before: { type: "string" }, acquired_after: { type: "string" }, acquired_before: { type: "string" }, snippet_max_length: { type: "integer", minimum: 180, maximum: 10000 } } }, outputSchema: { oneOf: [errorSchema, { type: "object", additionalProperties: false, required: ["ok", "source", "query", "results"], properties: { ok: { const: true }, source: { const: "keenable" }, query: { type: "string" }, results: { type: "array", items: searchResultSchema } } }] } },
  fetch_page_content: { inputSchema: { type: "object", additionalProperties: false, required: ["url"], properties: { url: { type: "string", minLength: 1 }, live: { type: "boolean" }, max_chars: { type: "integer", minimum: 1, maximum: 200000 }, prompt: { type: "string", maxLength: 2000 } } }, outputSchema: { oneOf: [errorSchema, { type: "object", additionalProperties: false, required: ["ok", "source", "url", "title", "content"], properties: { ok: { const: true }, source: { const: "keenable" }, url: { type: "string" }, title: { type: "string" }, content: { type: "string" } } }] } }
  ,research_concept: { inputSchema:{type:"object",additionalProperties:false,required:["concept","scope"],properties:{concept:{type:"string",minLength:1},scope:{type:"string",minLength:1},language:{enum:["zh-CN","en"]},audience:{enum:["beginner","intermediate","expert"]},depth:{enum:["brief","standard","deep"]},mathMode:mathModeSchema,max_sources_per_query:{type:"integer",minimum:1,maximum:5,default:3},max_iterations:{type:"integer",minimum:1,maximum:3,default:2},resume_run_id:{type:"string",minLength:1}}},outputSchema:{oneOf:[errorSchema,researchSuccessSchema]} }
  ,get_research_run: { inputSchema:{type:"object",additionalProperties:false,required:["run_id"],properties:{run_id:{type:"string",minLength:1}}},outputSchema:{oneOf:[errorSchema,researchSuccessSchema]} }
  ,export_concept_graph: { inputSchema:{type:"object",additionalProperties:false,required:["run_id"],properties:{run_id:{type:"string",minLength:1}}},outputSchema:{oneOf:[errorSchema,graphSchema]} }
};
const allowed: Record<string, string[]> = { plan_concept_research: ["concept", "language", "audience", "depth"], get_demo_concept: ["concept", "language"], validate_evidence_cards: ["cards"], render_concept_report: ["concept", "plan", "evidenceCards", "language", "mathMode"], search_web_pages: ["query", "site", "published_after", "published_before", "acquired_after", "acquired_before", "snippet_max_length"], fetch_page_content: ["url", "live", "max_chars", "prompt"], research_concept:["concept","scope","language","audience","depth","mathMode","max_sources_per_query","max_iterations","resume_run_id"],get_research_run:["run_id"],export_concept_graph:["run_id"] };
const remoteString = (value: unknown) => typeof value === "string";
function textFor(value: unknown) { return typeof value === "object" && value && "ok" in (value as Record<string, unknown>) && !(value as { ok: boolean }).ok ? `Error: ${(value as { error: { message: string } }).error.message}` : "Structured result returned."; }
function argumentsError(name: string, args: unknown) {
  if (!args || typeof args !== "object" || Array.isArray(args)) return toolError("INVALID_ARGUMENT", "Tool arguments must be an object / 工具参数必须是对象。"); const input = args as Record<string, unknown>; const keys = allowed[name]; if (!keys) return toolError("UNKNOWN_TOOL", `Unknown tool: ${name}`); const extra = Object.keys(input).filter((key) => !keys.includes(key)); if (extra.length) return toolError("UNKNOWN_PROPERTY", "Tool arguments do not permit undeclared properties / 工具参数不允许未声明字段。", { paths: extra });
  if (name === "plan_concept_research" && (typeof input.concept !== "string" || !input.concept.trim() || (input.language !== undefined && !["zh-CN", "en"].includes(String(input.language))) || (input.audience !== undefined && !["beginner", "intermediate", "expert"].includes(String(input.audience))) || (input.depth !== undefined && !["brief", "standard", "deep"].includes(String(input.depth))))) return toolError("INVALID_ARGUMENT", "plan_concept_research arguments do not match schema.");
  if (name === "get_demo_concept" && (!["entropy", "熵"].includes(String(input.concept)) || (input.language !== undefined && input.language !== "zh-CN"))) return toolError("INVALID_ARGUMENT", "Only the zh-CN entropy demo is bundled / 仅内置 zh-CN 熵演示。");
  if (name === "validate_evidence_cards" && !Array.isArray(input.cards)) return toolError("INVALID_ARGUMENT", "cards must be an array / cards 必须是数组。");
  if (name === "render_concept_report" && (typeof input.concept !== "string" || !input.concept.trim() || !input.plan || typeof input.plan !== "object" || Array.isArray(input.plan) || !Array.isArray(input.evidenceCards) || (input.language !== undefined && !["zh-CN", "en"].includes(String(input.language))) || (input.mathMode !== undefined && !isMathMode(input.mathMode)))) return toolError("INVALID_ARGUMENT", "render_concept_report arguments do not match schema.");
  if (name === "search_web_pages" && (typeof input.query !== "string" || !input.query.trim() || ["site", "published_after", "published_before", "acquired_after", "acquired_before"].some((key) => input[key] !== undefined && !remoteString(input[key])) || (input.snippet_max_length !== undefined && (!Number.isInteger(input.snippet_max_length) || input.snippet_max_length < 180 || input.snippet_max_length > 10000)))) return toolError("INVALID_ARGUMENT", "search_web_pages arguments do not match schema.");
  if (name === "fetch_page_content" && (typeof input.url !== "string" || !input.url.trim() || (input.live !== undefined && typeof input.live !== "boolean") || (input.max_chars !== undefined && (!Number.isInteger(input.max_chars) || input.max_chars < 1 || input.max_chars > 200000)) || (input.prompt !== undefined && (typeof input.prompt !== "string" || input.prompt.length > 2000)))) return toolError("INVALID_ARGUMENT", "fetch_page_content arguments do not match schema.");
  if (name === "research_concept" && (typeof input.concept!=="string"||!input.concept.trim()||typeof input.scope!=="string"||!input.scope.trim()||(input.mathMode!==undefined&&!isMathMode(input.mathMode))||(input.resume_run_id!==undefined&&(typeof input.resume_run_id!=="string"||!input.resume_run_id.trim())))) return toolError("INVALID_ARGUMENT","research_concept arguments do not match schema.");
  if ((name === "get_research_run" || name === "export_concept_graph") && (typeof input.run_id!=="string"||!input.run_id.trim())) return toolError("INVALID_ARGUMENT",`${name} arguments do not match schema.`);
  return null;
}
function demo() { const base = fixture as { concept: string; lastReviewed: string; plan: unknown; evidenceCards: unknown[] }; const result = renderConceptReport({ concept: "熵", plan: base.plan, evidenceCards: base.evidenceCards }); if (!result.ok) return result; const label = { kind: "demo-fixture", lastReviewed: base.lastReviewed, freshness: "bundled-offline-fixture" }; const report = { demo: true as const, provenance: label, report: { ...result.report, markdown: `> **演示 fixture（离线、非实时）**｜最后复核：${base.lastReviewed}\n\n${result.report.markdown}` } }; return { ok: true as const, demo: true as const, provenance: label, dataset: { demo: true as const, provenance: label, concept: base.concept, plan: base.plan, evidenceCards: base.evidenceCards.map((card) => ({ demo: true as const, provenance: label, card })) }, report, validation: { demo: true as const, provenance: label, validation: result.validation } }; }
let researchEngine: ResearchEngine | undefined;
export function setResearchEngineForTests(value?: ResearchEngine) { researchEngine=value; }
export async function executeTool(name: string, args: unknown) { const error = argumentsError(name, args); if (error) return error; const input = args as Record<string, unknown>; if (name === "plan_concept_research") return planConceptResearch(input); if (name === "get_demo_concept") return demo(); if (name === "validate_evidence_cards") return validateEvidenceCards(input.cards); if (name === "render_concept_report") return renderConceptReport(input); if (name === "search_web_pages") return searchWebPages(input as Parameters<typeof searchWebPages>[0]); if(name==="fetch_page_content") return fetchPageContent(input as Parameters<typeof fetchPageContent>[0]); const engine=researchEngine??(researchEngine=new ResearchEngine()); if(name==="research_concept") return engine.run(input); if(name==="get_research_run") return engine.get(String(input.run_id)); return engine.graph(String(input.run_id)); }
export const tools = Object.entries(toolSchemas).map(([name, schema]) => ({ name, description: `Concept Atlas: ${name}`, ...schema }));
export async function handleRequest(request: Record<string, unknown>) {
  const notification = !Object.prototype.hasOwnProperty.call(request, "id"); const id = request.id ?? null;
  if (request.jsonrpc !== "2.0" || typeof request.method !== "string") return notification ? null : { jsonrpc: "2.0", id, error: { code: -32600, message: "Invalid Request" } };
  if (request.method === "initialize") return notification ? null : { jsonrpc: "2.0", id, result: { protocolVersion: String((request.params as Record<string, unknown> | undefined)?.protocolVersion ?? "2024-11-05"), capabilities: { tools: {} }, serverInfo: { name: "concept-atlas", version: VERSION } } };
  if (request.method === "tools/list") return notification ? null : { jsonrpc: "2.0", id, result: { tools } };
  if (request.method === "tools/call") { const params = request.params as Record<string, unknown> | undefined; const value = await executeTool(String(params?.name ?? ""), params?.arguments ?? {}); return notification ? null : { jsonrpc: "2.0", id, result: { content: [{ type: "text", text: textFor(value) }], structuredContent: value, isError: !value.ok } }; }
  return notification ? null : { jsonrpc: "2.0", id, error: { code: -32601, message: "Method not found" } };
}
function write(message: unknown) { process.stdout.write(`${JSON.stringify(message)}\n`); }
if (import.meta.main) { let buffer = ""; let pending = Promise.resolve(); process.stdin.setEncoding("utf8"); process.stdin.on("data", (chunk) => { buffer += chunk; const lines = buffer.split("\n"); buffer = lines.pop() ?? ""; for (const line of lines) pending = pending.then(async () => { if (!line.trim()) return; try { const parsed = JSON.parse(line); if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) { write({ jsonrpc: "2.0", id: null, error: { code: -32600, message: "Invalid Request" } }); return; } const result = await handleRequest(parsed as Record<string, unknown>); if (result) write(result); } catch { write({ jsonrpc: "2.0", id: null, error: { code: -32700, message: "Parse error" } }); } }); }); }
